lttng-ust-generate: use latest version of bindgen
This is to fix the following error, assuming you have a package called
your_package:

error: multiple packages link to native library `clang`, but a native library can be linked only once

package `clang-sys v0.21.2`
    ... which satisfies dependency `clang-sys = "=0.21.2"` of package `bindgen v0.32.3`
    ... which satisfies dependency `bindgen = "=0.32.3"` of package `lttng-ust-generate v0.1.1`
    ... which satisfies dependency `lttng-ust-generate = "=0.1.1"` of package `your_package v0.1.0`
links to native library `clang`

package `clang-sys v1.3.0`
    ... which satisfies dependency `clang-sys = "=1.3.0"` of package `bindgen v0.58.1`
    ... which satisfies dependency `bindgen = "=0.58.1"` of package `your_package v0.1.0`
also links to native library `clang`